#!/usr/bin/env python3

import argparse
import logging
import os

from finmanlib.repl import FinmanREPL


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
            prog="finman",
            description="View/edit Finman files")
    parser.add_argument(
            'jsonl',
            nargs='+',
            metavar='JSONL',
            help="Finman JSONL transaction files")
    parser.add_argument(
            '--cat',
            help="Finman categories file")

    return parser.parse_args()


if __name__ == "__main__":
    level = os.getenv("FINMAN_DEBUG", "info").lower()
    level = {
        "debug":   logging.DEBUG,
        "info":    logging.INFO,
        "warning": logging.WARNING,
        "error":   logging.ERROR
    }[level]
    logging.basicConfig(level=level, format="%(message)s")

    args = get_args()
    FinmanREPL(args).run()
